os:
  - linux
  - osx

matrix:
  include:
    # Different distros and compilers on amd64
    - os: linux
      dist: focal
      arch: amd64
      compiler: gcc
    - os: linux
      dist: focal
      arch: amd64
      compiler: clang
    # Different architectures, gcc only
    - os: linux
      dist: focal
      arch: arm64
    - os: linux
      dist: focal
      arch: ppc64le
    - os: linux
      dist: focal
      arch: s390x
    - os: linux
      dist: bionic
      arch: amd64
    - os: osx
  exclude:
    # Doesn't have min cmake version
    - os: linux
      dist: xenial

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libftdi-dev
      - libhidapi-dev
  homebrew:
    packages:
      - libftdi
      - hidapi
    update: true

install:
  # raplcap dependency
  - git clone https://github.com/powercap/raplcap.git
  - cd raplcap
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=_install ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cmake --build . --target install; fi
  - cd ../..

script:
  - mkdir _build
  - cd _build
    # Test build with stricter flags
  - export CFLAGS="-D_FORTIFY_SOURCE=2 -fstack-protector -g3 -pedantic -W -Wall -Wbad-function-cast -Wcast-align
      -Wcast-qual -Wdisabled-optimization -Wendif-labels -Wfloat-equal -Wformat=2 -Wformat-nonliteral -Winline
      -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unused-parameter -Wpointer-arith -Wshadow
      -Wstrict-prototypes -Wstack-protector -Wswitch -Wundef -Wwrite-strings"
  - PKG_CONFIG_PATH="../raplcap/_build/_install/lib/pkgconfig" cmake .. -DCMAKE_C_FLAGS="$CFLAGS"
  - cmake .. -DCMAKE_C_FLAGS="$CFLAGS"
  - cmake --build .
